src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @ORM\Column(type="text")
     */
    private $Content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Author;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
    // pour l'url de l'image
    public function __toString()
    {
        return $this->Image;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Title')
            ->add('Image')
            ->add('Content')
            ->add('CreatedAt')
            ->add('Author')
            ->add('save', SubmitType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    /**
     * @Route("/article", name="article")
     */
    public function index() :  Response
    {
        $repo = $this->getDoctrine()->getRepository(Article::class);
       // dump($repo);
        $article = $repo->findAll();
        return $this->render('article/index.html.twig', [
        'article' => $article,
            'controller_name'=>'Articles'
        ]);
    }
    /**
     * @Route("/detail/{article}", name="article-detail")
     */
    public function showArticle(Article $article)
    {
        return $this->render('article/articledetail.html.twig', [
            'controller_name' => 'les détails de l\'article',
            'article'=> $article
        ]);
    }

    /**
     * @Route("/article/add", name="article-add", requirements={"article"="^(?!register).+"})
     */
    //@Route("/article/{article}", name="addarticle", requirements={"article"="^(?!register).+"})
    public function addArticle(Request $request)
    {
        $form = $this->createForm(ArticleType::class, new Article());
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $article = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($article);
            $em->flush();
        } else {
                return $this->render('admin/addarticle.html.twig', [
                'form' => $form->createView(),
                'errors' => $form->getErrors()

            ]);
        }
        return $this->render('home/index.html.twig') ;
    }

}

templates/article/addarticle.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="example-wrapper">
        <h1>Ajouter un article</h1>

        {{ form(form) }}

    </div>
{% endblock %}

templates/article/articledetail.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="example-wrapper">
        <h1> {{ article.title }}</h1>
        <img src="{{ article.image }}">
        <p>{{ article.content }}</p>
        <h6>Article écrit le {{ article.created_at }} par {{ article.author }} .</h6>



    </div>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArticleController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

    <div class="example-wrapper">
    <div class="jumbotron">
        <h1>Tout les {{ controller_name }}! </h1>

    </div>

    </div>
    <div class="row">
        <ul>
            {% for art in article %}
                <div class="col-3" style="width: 18rem;">
                    <img  src="{{ art.image}}" alt="image">
                    <h5>{{ art.title }}</h5>
                    <a href="{{ path('article-detail', {'article': art.id}) }}" class="btn btn-primary">Détail article</a>
                </div>
            {% endfor %}

        </ul>
    </div>
{% endblock %}